FROM scratch

LABEL maintainer ${MAINTAINER}
LABEL type "public"
LABEL versioning "simple"

ARG TOOL

ADD ./build/ /
COPY ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ENTRYPOINT ["./app"]