[[constraint]]
  branch = "master"
  name = "github.com/kolide/kit"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.22.0"

[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  branch = "master"
