apiVersion: v1
kind: Secret
metadata:
  name: hangouts-jira-bot
  labels:
    app: hangouts-jira-bot
    k8s.seibert-media.io/priority: "low"
  annotations:
    k8s.seibert-media.io/owner: "Team Google <team-google@seibert-media.net>"
    k8s.seibert-media.io/source: "https://github.com/seibert-media/hangouts-jira-bot"
    k8s.seibert-media.io/description: "A Google Chat bot for interacting with Jira Issues."
    k8s.seibert-media.io/docs: "https://github.com/seibert-media/hangouts-jira-bot"
data:
  key.json: '{{"mQ4Jag" | teamvaultFile | base64}}'
  jira-url: '{{"m83z5g" | teamvaultUrl | base64}}'
  jira-username: '{{"m83z5g" | teamvaultUser | base64}}'
  jira-password: '{{"m83z5g" | teamvaultPassword | base64}}'
  sentry-dsn: '{{"0zD2Ag" | teamvaultPassword | base64}}'
type: Opaque
